### ISSUE TITLE
Error reported when d_state is set to a value other than 1.

### ISSUE THREAD

**Issue by PWang2002** [EdwardChasel/Spatial-Mamba#2]
Error reported when d_state is set to a value other than 1.
When the d_state is set to a value other than 1, how to reshape the hidden state h in Line 269 of the file Spatial-Mamba/classification/models/spatialmamba.py so that h can be multiplied by Cs?
Looking forward to your reply, thanks!

**Comment by EdwardChasel** [comment]
Due to the GPU memory and efficiency constraints, the current version only supports a dstate value of 1. We are working on optimizing the CUDA kernels to support different dstates soon.

**Comment by PWang2002** [comment]
> Due to the GPU memory and efficiency constraints, the current version only supports a dstate value of 1. We are working on optimizing the CUDA kernels to support different dstates soon.

Thank you for your response. Looking forward to your next releases!

**Comment by olex-ui** [comment]
I found that when the value of d_state exceeds 18, an error occurs: "RuntimeError: CUDA error: an illegal memory access was encountered. CUDA kernel errors might be asynchronously reported at some other API call, so the stack trace below might be incorrect."
