### ISSUE TITLE
Visulization

### ISSUE THREAD

**Issue by weilli** [EdwardChasel/Spatial-Mamba#3]
Thanks for your excellent work. I was wondering how to generate "Figure 5: Visualization of matrices M for linear attention, Mamba and Spatial-Mamba." Could you open the related code? Thanks again.

**Comment by EdwardChasel** [comment]
Sorry for the late reply, we just use the simplest `for loop` to calculate the value of each ij-th position according to the corresponding derived equations, though it's time-consuming. You can see [here](https://github.com/AmeenAli/HiddenMambaAttn/blob/77739efbf4f29cd61eaa381a21446744e069dac4/mamba-1p1p1/mamba_ssm/ops/selective_scan_interface.py#L741) for a reference and then try it by yourself.
