### ISSUE TITLE
can't install Dwconv

### ISSUE THREAD

**Issue by 1220wangyi** [EdwardChasel/Spatial-Mamba#8]
in readme, can't install cd kernels/dwconv2d && python3 setup.py install --user,

**Comment by EdwardChasel** [comment]
Please check your environment setup and refer to issue https://github.com/EdwardChasel/Spatial-Mamba/issues/1 and [requirements.txt](https://github.com/EdwardChasel/Spatial-Mamba/blob/main/requirements.txt) for more details.
